version: "3.9"

services:
  anime-sama:
    build: .
    container_name: anime-sama
    ports:
      - "3000:3000"
    volumes:
      - ./adapters/web/back/downloads:/app/adapters/web/back/downloads
    restart: unless-stopped